name = "ppk-drivehub"
compatibility_date = "2024-11-01"
pages_build_output_dir = "./dist"

[vars]
JWT_SECRET = "PPK2569-DH-8x2k9m4p7-n1q5v3t6w0a1r4-j8"
SYSTEM_NAME = "PPK DriveHub"

[[d1_databases]]
binding = "DB"
database_name = "ppk-drivehub-db"
database_id = "4b18fad9-15f5-4741-bfa1-877fb34a8298"
