-- PPK DriveHub — Production DB Reset
-- Drop all old UPPERCASE tables and extras, then recreate with new schema

DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS AUDIT_LOG;
DROP TABLE IF EXISTS CARS;
DROP TABLE IF EXISTS CHECK_LOG;
DROP TABLE IF EXISTS DRIVERS;
DROP TABLE IF EXISTS FUEL_LOG;
DROP TABLE IF EXISTS FUEL_REQUESTS;
DROP TABLE IF EXISTS INSPECTION_ALERTS;
DROP TABLE IF EXISTS INSURANCE_RECORDS;
DROP TABLE IF EXISTS LEAVES;
DROP TABLE IF EXISTS MAINTENANCE_SETTINGS;
DROP TABLE IF EXISTS MASTER;
DROP TABLE IF EXISTS NOTIFICATIONS;
DROP TABLE IF EXISTS PASSWORD_HISTORY;
DROP TABLE IF EXISTS PDPA_LOG;
DROP TABLE IF EXISTS QUEUE;
DROP TABLE IF EXISTS QUEUE_RULES;
DROP TABLE IF EXISTS REPAIR_LOG;
DROP TABLE IF EXISTS RESET_PASSWORD_REQUESTS;
DROP TABLE IF EXISTS SCHEDULED_REPAIRS;
DROP TABLE IF EXISTS SELF_REPORTED_FATIGUE;
DROP TABLE IF EXISTS SYSTEM_SNAPSHOT;
DROP TABLE IF EXISTS TAX_RECORDS;
DROP TABLE IF EXISTS USAGE_RECORDS;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS USER_REQUESTS;
DROP TABLE IF EXISTS VEHICLE_MAINTENANCE;
DROP TABLE IF EXISTS SYSTEM_SETTINGS;
DROP TABLE IF EXISTS BACKUPS;
